console.log("Inicio Programa");
var preguntas = 3;
var preguntasFaltantes = "Quedan " + preguntas + " preguntas.";
alert("Este es el juego del cuenta cuentos. Sigue las instrucciones.");
var sustantivo = prompt("Estimado usuario, Ingrese un sustantivo. "+ preguntasFaltantes);
preguntas=preguntas-1;
preguntasFaltantes="Quedan " + preguntas + " preguntas.";
var verbo = prompt ("Estimado usuario, Ingrese un verbo. "+preguntasFaltantes);
preguntas=preguntas-1;
preguntasFaltantes="Quedan " + preguntas + " preguntas.";
var adjetivo = prompt ("Estimado usuario, Ingrese un adjetivo. "+preguntasFaltantes);
document.write("<h1>Cuenta cuentos</h1><br>");
document.write("<p>El "+sustantivo+" "+adjetivo+" "+verbo+" locamente,</p>");
document.write("<p>porque cuando "+verbo+" el "+sustantivo+" siempre es "+adjetivo+",</p>");
document.write("<p>por eso el "+sustantivo+" siente que es muy "+adjetivo+" y es así que cada día "+verbo+" que "+verbo+".</p>");
console.log("Fin Programa");